### ISSUE TITLE
Issues with setup - errors thrown running sample scenes in editor, issues with camera input simulation

### ISSUE THREAD

**Issue by chrisfromwork** [provencher/MRTK-Quest-Sample#2] opened 2020-06-21 18:09 UTC
So, I wanted to try out this project but hit some issues. I have never used oculus before, so I can't say that my local setup is correct. Thus far, I have hit two issues trying to run the sample scenes:

XR: OpenVR Error! OpenVR failed initialization with error code VRInitError_Init_PathRegistryNotFound: "Installation path could not be located (110)"!

DllNotFoundException: libovravatar
OvrAvatarSDKManager.Initialize () (at Assets/Oculus/Avatar/Scripts/OvrAvatarSDKManager.cs:102)
OvrAvatarSDKManager.get_Instance () (at Assets/Oculus/Avatar/Scripts/OvrAvatarSDKManager.cs:75)
OvrAvatar.Start () (at Assets/Oculus/Avatar/Scripts/OvrAvatar.cs:550)

I'm not sure if these two issues are known/ignorable. I think the first issue may be related to not having steam installed? Or at least I have had similar issues with the MRTK when not installing steam. The second seems like it may be related to never having installed any of the oculus software on my PC.

Regardless, hand input simulation seems to work in play mode for the sample scenes. I was anticipating that I could move the HMD camera with a mouse + scroll wheel but that doesnt appear to work. Does MRTK HMD camera input simulation not work for oculus?

**Comment by chrisfromwork** [comment] 2020-06-21 18:12
input simulation appears to work if you use ctrl/alt keys for the camera HMD, so this may just be me needing to get more familiar with the MRTK as well. Regaredless, if there are suggestions for these two errors, itd be great to hear whats suggested

**Comment by chrisfromwork** [comment] 2020-06-21 18:14
granted in terms of simulated input, it seems like the scroll wheel only moves the HMD camera up and down compared to in the forward direction of the camera

**Comment by provencher** [comment] 2020-06-21 19:08
Hi Chris! 

Thanks for writing up this issue!

The error you’re pointing to shows up when trying to use OpenVR, which isn’t supported by this extension at the moment. Perhaps the issue is that you’re running in windows standalone, which is marked as supported with the MRTK-Quest device provider, and causes conflicts with the built in MRTK openvr support. 

I’m not sure of the best way to resolve this, but in my MRTK-Quest profile I remove the openVR device manager for this reason.

Regarding editor simulation, yeah it’s not currently supported, and I haven’t bothered to debug it given most users debug their scenes with oculus link or a rift.

**Comment by provencher** [comment] 2020-06-22 16:26
Also for future reference, please create MRTK-Quest issues [here](https://github.com/provencher/MRTK-Quest/issues). This repo is simply to help debug user setups or quickly test the unity integration. Actual dev work happens on the proper MRTK-Quest repo.

**Comment by chrisfromwork** [comment] 2020-06-23 00:23
sounds good! i do not have a link cable but i was able to generate a usable APK. thanks for piecing this sample together!

**Comment by provencher** [comment] 2020-06-23 23:27
Glad it was helpful to you :)
While you're here - I'd like you to pay attention to the way icons in the 3D don't mipmap correctly with the Quest's lower resolution panel, and most UI is unreadable by default, unless you're very close to them.

We need to figure out a way to super sample it.

**Comment by provencher** [comment] 2020-10-28 13:21
With the latest change to the 2.5.1 integration, this issue is no longer relevant. Closing

**Closed as completed by provencher** 2020-10-28 13:21 UTC

**Comment by skyzdev** [comment] 2021-01-25 16:15
@provencher hey Eric, there are some new deployment issues introduced with MRTK 2.5 XR SDK, so I am currently working with MRTK 2.4 and MRTK-Quest for my project, but this error keeps on popping up. Is there a way to address this libovravatar DLL not found issue for MRTK 2.4?

**Comment by provencher** [comment] 2021-01-25 16:16
I would reimport your oculus sdk. It sounds like an issue with the oculus DLL not being properly imported. I don't have that error personally.

**Comment by skyzdev** [comment] 2021-01-25 16:26
Thanks! Let me clarify, the error pops up under non-Android platforms... I tried adding conditional compile flags, but the OVR Avatar's  chain of function calls runs really deep...

**Comment by provencher** [comment] 2021-01-25 16:46
Hmm this might be a weird bit of advice, but MRTK 2.5 has the compile flags, so you can write your code for quest no problem.

It might be good to have a separate Unity project without the ovr plugin, and then one with it for Quest dev. Each builds their own platform and your codebase can stay in sync with source control.

I'll share this feedback with some folks at MS btw.

**Comment by RogPodge** [comment] 2021-01-28 16:17
@skyzdev hey there, we recommend you use the latest MRTK packages on Unity 2019. I also remember seeing some of those libovravatar errors before, but haven't encountered them since 2.5.x. If it turns out that there's a new issue that's blocking deployments, we'd love to know about it so we can figure out how to fix it :D
